-- Arda Link — environmental data for prediction (migration 010)
--
-- Why this migration exists: until now the system was purely descriptive — one
-- Sentinel-2 snapshot of "now", overwritten every 14 days, with no rainfall,
-- soil moisture or forecast anywhere. That makes prediction impossible (there is
-- no history and no environmental driver), and it also makes us unable to VALIDATE
-- any future claim. This migration starts the clock.
--
-- Adds:
--   water_sources.indices_as_of   - the date the satellite snapshot was taken
--                                   (honesty: we can say how stale the pasture
--                                   data is instead of implying it is "now")
--   rainfall_climatology          - per water point, per calendar month, the
--                                   30-year CHIRPS normal (mean + p10/p90), so a
--                                   dry spell can be compared with what is normal
--                                   FOR THAT MONTH AND PLACE, not in the abstract
--   environment_daily             - observed daily rainfall / soil moisture per
--                                   water point (the predictor's input series)
--   environment_forecast          - CACHED forecast per water point (16-day), so
--                                   the request path never calls a weather API
--                                   live (architecture principle #1: FastAPI only
--                                   reads precomputed data)
--
-- RLS: same posture as 001-009 — enabled + forced, no anon policies (the backend
-- talks through the service_role key by design).

alter table water_sources add column if not exists indices_as_of date;

-- ============================================================================
-- rainfall_climatology: what "normal rain" means for THIS point in THIS month.
-- source is recorded because the series may later come from CHIRPS (GEE) or
-- Open-Meteo, and a climatology must never be mixed across sources silently.
-- ============================================================================
create table if not exists rainfall_climatology (
  water_source_id uuid not null references water_sources(id) on delete cascade,
  month           int  not null check (month between 1 and 12),
  mean_mm         numeric(8,2) not null,
  p10_mm          numeric(8,2),
  p90_mm          numeric(8,2),
  years           int  not null,
  source          text not null default 'chirps',
  updated_at      timestamptz not null default now(),
  primary key (water_source_id, month)
);

alter table rainfall_climatology enable row level security;
alter table rainfall_climatology force row level security;

-- ============================================================================
-- environment_daily: one row per water point per day of observed rain.
-- This is the series a predictor needs and the only thing we cannot backfill
-- once the day has passed for a given source/API revision.
-- ============================================================================
create table if not exists environment_daily (
  water_source_id uuid not null references water_sources(id) on delete cascade,
  observed_on     date not null,
  rain_mm         numeric(8,2),
  soil_moisture   numeric(8,4),
  source          text not null default 'open-meteo',
  created_at      timestamptz not null default now(),
  primary key (water_source_id, observed_on)
);

create index if not exists idx_environment_daily_date on environment_daily (observed_on desc);

alter table environment_daily enable row level security;
alter table environment_daily force row level security;

-- ============================================================================
-- environment_forecast: the latest cached forecast for a water point.
-- daily is a jsonb list: [{"date": "2026-09-18", "rain_mm": 0.0}, ...]
-- Regenerated by scripts/refresh_environment.py (scheduled), never by a request.
-- ============================================================================
create table if not exists environment_forecast (
  water_source_id uuid primary key references water_sources(id) on delete cascade,
  generated_at    timestamptz not null default now(),
  horizon_days    int not null,
  total_mm        numeric(8,2),
  daily           jsonb not null default '[]'::jsonb,
  source          text not null default 'open-meteo'
);

alter table environment_forecast enable row level security;
alter table environment_forecast force row level security;
